# SyInfo Monitoring Configuration
# This file contains the default configuration for the monitoring system

monitoring:
  # System monitoring settings
  system:
    enabled: true
    interval: 60  # seconds
    metrics:
      - cpu_usage
      - memory_usage
      - disk_usage
      - network_io
    
  # Process monitoring settings
  process:
    enabled: true
    interval: 60  # seconds
    top_processes: 10
    filter_pattern: null  # Optional regex pattern to filter processes
    
  # Log monitoring settings
  logs:
    enabled: false  # Disabled by default for security
    sources:
      - /var/log/syslog
      - /var/log/auth.log
    max_lines: 1000
    
  # Storage settings
  storage:
    data_directory: "/var/log/syinfo/monitoring"
    retention_days: 7
    format: "csv"  # csv or json
    compression: false
    max_file_size: "100MB"
    
  # Logging settings
  logging:
    level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
    file: "/var/log/syinfo/monitoring.log"
    max_size: "10MB"
    backup_count: 5
    console_output: true
    
  # Alerting settings
  alerts:
    enabled: false
    thresholds:
      cpu_percent: 80
      memory_percent: 80
      disk_percent: 90
    email:
      enabled: false
      smtp_server: "localhost"
      smtp_port: 587
      username: ""
      password: ""
      recipients: []
    
  # Performance settings
  performance:
    max_memory_usage: "512MB"
    max_cpu_percent: 10
    timeout_seconds: 30
    
  # Security settings
  security:
    allowed_directories:
      - "/var/log"
      - "/tmp"
      - "/home"
    restricted_commands: []
    require_sudo: false 